### PR TITLE
Install dependencies with aptitude

### PR DESCRIPTION
**Pull request by kerrermanisNL**
Allows us to solve problems automatically if there are missing deps
Also use new docker registry for builddocker

### CODE REVIEW

**Review by Erik-Lamers1 — COMMENTED** [review]
Not sure if the docker URL is correct

**Comment by kerrermanisNL** [comment]
Hm, these are the possible options, not sure which to use:
```

0 | "hypernode-auth"
-- | --
1 | "hypernode-control-panel"
2 | "hypernode-servicepanel"
3 | "jessie"
4 | "library/event-triggered-mailer-dev"
5 | "magento-base"
6 | "prov/base-wheezy"
7 | "rabbitmq-management"
8 | "v2/dev/perl-python-compatibility-tests"
9 | "v2/magento_base"
10 | "v2/prov/auth.byte.nl"
11 | "v2/prov/base-wheezy"
12 | "v2/prov/byte-debian"
13 | "v2/prov/byte-jessie"
14 | "v2/prov/byte-wheezy"
15 | "v2/prov/coneybeach"
16 | "v2/prov/haruspex"
17 | "v2/prov/hypernode-api"
18 | "v2/prov/hypernode-control"
19 | "v2/prov/officetools"
20 | "v2/prov/pdns-fixture"
21 | "v2/prov/pino"
22 | "v2/prov/quickscan"
23 | "v2/prov/servicepanel-perl"
24 | "v2/prov/servicepanel-python"
```
`byte-wheezy` maybe?

**Comment by Erik-Lamers1** [comment]
Yes that's the one I used recently. apparently that still works :muscle:

**Comment by kerrermanisNL** [comment]
@Erik-Lamers1 amended

**Review by Erik-Lamers1 — APPROVED** [review]

**Pull request merged**
